name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/Backend/**'
      - 'src/Backend/Dockerfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/Backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      with:
        context: src/Backend
        file: src/Backend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository  | lower }}/backend:latest
          ghcr.io/${{ github.repository  | lower }}/backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

